language: java

cache:
    directories:
        - "$HOME/.m2"

script: "mvn verify"
<<<<<<< refs/remotes/origin/master
after_success:
- bash <(curl -s https://codecov.io/bash)
=======

after_success:
- bash <(curl -s https://codecov.io/bash)
>>>>>>> Heberge
